### ISSUE TITLE
按照你的efi安装成功了，但是现在睡眠还是有点问题

### ISSUE THREAD

**Issue by leihuazhe** [ettingshausen/k43c-80-hackintosh#2]
睡眠一段时间后会自动重启或自己黑屏，你是怎么解决的？

**Comment by ettingshausen** [comment]
我没有启用过睡眠，刚试了一下确实有这个问题。我会尝试这解决一下。
如果你解决好了，欢迎PR

**Comment by ettingshausen** [comment]
```
kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: GLAN XDCI
```
问题应该是 `GLAN`  `XDCI` 所致，需要打一下 [0D/6D 补丁](https://github.com/daliansky/OC-little/tree/master/12-060D%E8%A1%A5%E4%B8%81/12-1-%E6%99%AE%E9%80%9A%E7%9A%84060D%E8%A1%A5%E4%B8%81)

**Comment by ettingshausen** [comment]
Fixed bb3299db9a17c59865fef6afbe1f01a7dd9d2bdd
